### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by Guirdo** [joromsar/clone_pinterest#1]
Veo que repites muchas veces los mismos estilos con diferente nombre de clases. 

Esta clase contiene los mismos estilos

```css
.bullets-link {
  background-color: #f1f1f1;
  color: #000;
  padding: 8px;
  border-radius: 50%;
  position: absolute;
  height: 15px;
  font-size: 15px;
  width: 15px;
  font-weight: bold;
  display: flex;
  align-content: center;
  justify-content: center;
  text-align: center;
  align-items: center;
}
```

Que esta otra:

```css
.bullets-link30 {
  background-color: #f1f1f1;
  color: #000;
  padding: 8px;
  border-radius: 50%;
  position: absolute;
  height: 15px;
  font-size: 15px;
  width: 15px;
  font-weight: bold;
  display: flex;
  align-content: center;
  justify-content: center;
  text-align: center;
  align-items: center;
}
```

Me pregunto por qué lo has hecho así, pues te podrías valer de una sola clase y reutilizarla en tu HTML cuantas veces necesitaras.
